# Generated by Django 5.0 on 2023-12-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.TextField(default='tvm')),
                ('features', models.TextField(default='superb')),
                ('flats_1bhk', models.PositiveIntegerField(default=0)),
                ('flats_2bhk', models.PositiveIntegerField(default=0)),
                ('flats_3bhk', models.PositiveIntegerField(default=0)),
                ('flats_4bhk', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RentalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK')], default='1BHK', max_length=5)),
                ('agreement_end_date', models.DateField()),
                ('monthly_rent_date', models.DateField()),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estate_admin.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate_admin.tenant')),
            ],
        ),
    ]
