# Generated by Django 5.0 on 2023-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_admin', '0003_property_cost_1bhk_property_cost_2bhk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tenant_documents'),
        ),
    ]
